/**
 * NexaSites — Centralized country configuration
 * Phase 1: English-speaking markets
 * Extend by adding a new entry; do not hardcode in components.
 */
window.NexaCountries = {
  defaultCountry: 'us',

  list: {
    us: {
      code: 'us',
      name: 'United States',
      flag: '🇺🇸',
      primaryLanguage: 'en-US',
      languages: ['en-US'],
      currency: 'USD',
      currencySymbol: '$',
      currencyPosition: 'before',
      phoneCode: '+1',
      phoneExample: '+1 (415) 555-0132',
      phoneFormat: '(###) ###-####',
      dateFormat: 'MM/DD/YYYY',
      measurement: 'imperial',
      timezone: 'America/New_York',
      locale: 'en-US',
      regionLabel: 'US',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'cell',
        zip: 'ZIP code',
        state: 'state',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 299,
        growth: 449,
        pro: 599,
        display: { starter: '$299', growth: '$449', pro: '$599', range: '$299 – $599', from: 'From $299 / year' },
      },
      addressExample: '123 Market St, San Francisco, CA 94103',
      cityExamples: ['New York', 'Austin', 'Seattle', 'Miami'],
      seo: {
        title: 'NexaSites — AI Websites for US Businesses',
        description: 'Custom AI-built websites with domain included. Starting at $299/year for US businesses.',
      },
      demo: {
        cafe: {
          name: 'Harbor Roast',
          tagline: 'Neighborhood coffee, properly done',
          address: '214 Pine Street, Seattle, WA 98101',
          hours: 'Mon–Sun 7:00 AM – 8:00 PM',
          phone: '+1 (206) 555-0148',
          currency: '$',
          menu: [
            { name: 'Espresso', price: '$3.50' },
            { name: 'Oat Latte', price: '$5.25' },
            { name: 'Butter Croissant', price: '$4.00' },
            { name: 'Avocado Toast', price: '$12.00' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Austin, TX',
          phone: '+1 (512) 555-0199',
          plans: [
            { name: 'Basic', price: '$149', per: '/ mo' },
            { name: 'Pro', price: '$249', per: '/ mo' },
            { name: 'VIP', price: '$399', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Brooklyn, NY',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+1 (310) 555-0177',
          listings: [
            { title: 'Modern loft · Austin', meta: '3 bed · 1,850 sq ft', price: '$685,000' },
            { title: 'Oceanview condo · Miami', meta: '2 bed · balcony', price: '$920,000' },
            { title: 'Family home · Denver', meta: '4 bed · yard', price: '$740,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+1 (323) 555-0160',
          treatments: [
            { name: 'Classic facial', price: 'from $95' },
            { name: 'Anti-aging', price: 'from $150' },
            { name: 'Body treatment', price: 'from $120' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+1 (212) 555-0188',
          areas: ['Contracts', 'Real estate', 'Civil litigation'],
        },
      },
    },

    ca: {
      code: 'ca',
      name: 'Canada',
      flag: '🇨🇦',
      primaryLanguage: 'en-CA',
      languages: ['en-CA', 'fr-CA'],
      currency: 'CAD',
      currencySymbol: '$',
      currencyPosition: 'before',
      phoneCode: '+1',
      phoneExample: '+1 (416) 555-0134',
      phoneFormat: '(###) ###-####',
      dateFormat: 'YYYY-MM-DD',
      measurement: 'metric',
      timezone: 'America/Toronto',
      locale: 'en-CA',
      regionLabel: 'CA',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'cell',
        zip: 'postal code',
        state: 'province',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 399,
        growth: 599,
        pro: 799,
        display: { starter: 'C$399', growth: 'C$599', pro: 'C$799', range: 'C$399 – C$799', from: 'From C$399 / year' },
      },
      addressExample: '100 Queen St W, Toronto, ON M5H 2N2',
      cityExamples: ['Toronto', 'Vancouver', 'Montreal', 'Calgary'],
      seo: {
        title: 'NexaSites — AI Websites for Canadian Businesses',
        description: 'Custom AI-built websites with domain included. Starting at C$399/year across Canada.',
      },
      demo: {
        cafe: {
          name: 'Maple & Bean',
          tagline: 'A proper neighbourhood café',
          address: '482 Queen Street West, Toronto, ON M5V 2A8',
          hours: 'Mon–Sun 7:00 a.m. – 8:00 p.m.',
          phone: '+1 (416) 555-0190',
          currency: 'C$',
          menu: [
            { name: 'Espresso', price: 'C$3.75' },
            { name: 'Oat Latte', price: 'C$5.50' },
            { name: 'Butter Croissant', price: 'C$4.25' },
            { name: 'Avocado Toast', price: 'C$14.00' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Vancouver, BC',
          phone: '+1 (604) 555-0142',
          plans: [
            { name: 'Basic', price: 'C$179', per: '/ mo' },
            { name: 'Pro', price: 'C$279', per: '/ mo' },
            { name: 'VIP', price: 'C$449', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Toronto, ON',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+1 (416) 555-0175',
          listings: [
            { title: 'Condo · Downtown Toronto', meta: '2 bed · 950 sq ft', price: 'C$749,000' },
            { title: 'Townhouse · Vancouver', meta: '3 bed · patio', price: 'C$1,150,000' },
            { title: 'Family home · Calgary', meta: '4 bed · garage', price: 'C$625,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+1 (514) 555-0166',
          treatments: [
            { name: 'Classic facial', price: 'from C$110' },
            { name: 'Anti-aging', price: 'from C$175' },
            { name: 'Body treatment', price: 'from C$140' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+1 (416) 555-0180',
          areas: ['Contracts', 'Real estate', 'Civil litigation'],
        },
      },
    },

    uk: {
      code: 'uk',
      name: 'United Kingdom',
      flag: '🇬🇧',
      primaryLanguage: 'en-GB',
      languages: ['en-GB'],
      currency: 'GBP',
      currencySymbol: '£',
      currencyPosition: 'before',
      phoneCode: '+44',
      phoneExample: '+44 20 7946 0123',
      phoneFormat: '#### ######',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Europe/London',
      locale: 'en-GB',
      regionLabel: 'UK',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'telephone',
        mobile: 'mobile',
        zip: 'postcode',
        state: 'county',
        city: 'town',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 249,
        growth: 379,
        pro: 499,
        display: { starter: '£249', growth: '£379', pro: '£499', range: '£249 – £499', from: 'From £249 / year' },
      },
      addressExample: '14 Kingly Street, London W1B 5PR',
      cityExamples: ['London', 'Manchester', 'Edinburgh', 'Bristol'],
      seo: {
        title: 'NexaSites — AI Websites for UK Businesses',
        description: 'Bespoke AI-built websites with domain included. From £249/year for UK companies.',
      },
      demo: {
        cafe: {
          name: 'The Copper Kettle',
          tagline: 'Proper coffee, no fuss',
          address: '22 Brick Lane, London E1 6RF',
          hours: 'Mon–Sun 7:00 – 20:00',
          phone: '+44 20 7946 0155',
          currency: '£',
          menu: [
            { name: 'Espresso', price: '£2.80' },
            { name: 'Flat White', price: '£3.60' },
            { name: 'Butter Croissant', price: '£3.20' },
            { name: 'Avocado on Sourdough', price: '£9.50' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Manchester',
          phone: '+44 161 496 0120',
          plans: [
            { name: 'Basic', price: '£99', per: '/ mo' },
            { name: 'Pro', price: '£159', per: '/ mo' },
            { name: 'VIP', price: '£249', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Shoreditch, London',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+44 20 7946 0188',
          listings: [
            { title: 'Flat · Islington', meta: '2 bed · 75 m²', price: '£625,000' },
            { title: 'Terrace · Bristol', meta: '3 bed · garden', price: '£485,000' },
            { title: 'Apartment · Edinburgh', meta: '1 bed · city views', price: '£310,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+44 20 7946 0166',
          treatments: [
            { name: 'Classic facial', price: 'from £65' },
            { name: 'Anti-ageing', price: 'from £95' },
            { name: 'Body treatment', price: 'from £80' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+44 20 7946 0199',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    ie: {
      code: 'ie',
      name: 'Ireland',
      flag: '🇮🇪',
      primaryLanguage: 'en-IE',
      languages: ['en-IE'],
      currency: 'EUR',
      currencySymbol: '€',
      currencyPosition: 'before',
      phoneCode: '+353',
      phoneExample: '+353 1 234 5678',
      phoneFormat: '## ### ####',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Europe/Dublin',
      locale: 'en-IE',
      regionLabel: 'IE',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'Eircode',
        state: 'county',
        city: 'town',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 279,
        growth: 419,
        pro: 549,
        display: { starter: '€279', growth: '€419', pro: '€549', range: '€279 – €549', from: 'From €279 / year' },
      },
      addressExample: '12 Dame Street, Dublin 2, D02 XY45',
      cityExamples: ['Dublin', 'Cork', 'Galway', 'Limerick'],
      seo: {
        title: 'NexaSites — AI Websites for Irish Businesses',
        description: 'Custom AI-built websites with domain included. From €279/year in Ireland.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'A proper local coffee house',
          address: '18 Capel Street, Dublin 1',
          hours: 'Mon–Sun 7:30 – 19:00',
          phone: '+353 1 234 0155',
          currency: '€',
          menu: [
            { name: 'Espresso', price: '€2.90' },
            { name: 'Flat White', price: '€3.80' },
            { name: 'Butter Croissant', price: '€3.40' },
            { name: 'Avocado Toast', price: '€10.50' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Dublin',
          phone: '+353 1 234 0190',
          plans: [
            { name: 'Basic', price: '€110', per: '/ mo' },
            { name: 'Pro', price: '€175', per: '/ mo' },
            { name: 'VIP', price: '€275', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Dublin',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+353 1 234 0177',
          listings: [
            { title: 'Apartment · Dublin 2', meta: '2 bed · 80 m²', price: '€525,000' },
            { title: 'House · Cork', meta: '3 bed · garden', price: '€395,000' },
            { title: 'Cottage · Galway', meta: '2 bed · near bay', price: '€340,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+353 1 234 0166',
          treatments: [
            { name: 'Classic facial', price: 'from €70' },
            { name: 'Anti-ageing', price: 'from €105' },
            { name: 'Body treatment', price: 'from €90' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+353 1 234 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    au: {
      code: 'au',
      name: 'Australia',
      flag: '🇦🇺',
      primaryLanguage: 'en-AU',
      languages: ['en-AU'],
      currency: 'AUD',
      currencySymbol: '$',
      currencyPosition: 'before',
      phoneCode: '+61',
      phoneExample: '+61 2 8012 3456',
      phoneFormat: '# #### ####',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Australia/Sydney',
      locale: 'en-AU',
      regionLabel: 'AU',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'postcode',
        state: 'state',
        city: 'suburb',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 449,
        growth: 679,
        pro: 899,
        display: { starter: 'A$449', growth: 'A$679', pro: 'A$899', range: 'A$449 – A$899', from: 'From A$449 / year' },
      },
      addressExample: '42 Oxford Street, Darlinghurst NSW 2010',
      cityExamples: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
      seo: {
        title: 'NexaSites — AI Websites for Australian Businesses',
        description: 'Custom AI-built websites with domain included. From A$449/year across Australia.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighbourhood coffee, done properly',
          address: '88 Crown Street, Surry Hills NSW 2010',
          hours: 'Mon–Sun 6:30 am – 4:00 pm',
          phone: '+61 2 8012 0155',
          currency: 'A$',
          menu: [
            { name: 'Espresso', price: 'A$4.00' },
            { name: 'Flat White', price: 'A$5.00' },
            { name: 'Butter Croissant', price: 'A$5.50' },
            { name: 'Avocado Smash', price: 'A$18.00' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Melbourne',
          phone: '+61 3 9012 0142',
          plans: [
            { name: 'Basic', price: 'A$160', per: '/ mo' },
            { name: 'Pro', price: 'A$260', per: '/ mo' },
            { name: 'VIP', price: 'A$420', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Melbourne',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+61 2 8012 0177',
          listings: [
            { title: 'Apartment · Surry Hills', meta: '2 bed · 85 m²', price: 'A$1,150,000' },
            { title: 'Townhouse · Fitzroy', meta: '3 bed · courtyard', price: 'A$1,480,000' },
            { title: 'House · Brisbane', meta: '4 bed · pool', price: 'A$980,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+61 3 9012 0166',
          treatments: [
            { name: 'Classic facial', price: 'from A$120' },
            { name: 'Anti-ageing', price: 'from A$180' },
            { name: 'Body treatment', price: 'from A$150' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+61 2 8012 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    nz: {
      code: 'nz',
      name: 'New Zealand',
      flag: '🇳🇿',
      primaryLanguage: 'en-NZ',
      languages: ['en-NZ'],
      currency: 'NZD',
      currencySymbol: '$',
      currencyPosition: 'before',
      phoneCode: '+64',
      phoneExample: '+64 9 123 4567',
      phoneFormat: '# ### ####',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Pacific/Auckland',
      locale: 'en-NZ',
      regionLabel: 'NZ',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'postcode',
        state: 'region',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 449,
        growth: 679,
        pro: 899,
        display: { starter: 'NZ$449', growth: 'NZ$679', pro: 'NZ$899', range: 'NZ$449 – NZ$899', from: 'From NZ$449 / year' },
      },
      addressExample: '45 Queen Street, Auckland 1010',
      cityExamples: ['Auckland', 'Wellington', 'Christchurch', 'Queenstown'],
      seo: {
        title: 'NexaSites — AI Websites for New Zealand Businesses',
        description: 'Custom AI-built websites with domain included. From NZ$449/year in New Zealand.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighbourhood coffee, done properly',
          address: '12 Ponsonby Road, Auckland 1011',
          hours: 'Mon–Sun 7:00 am – 4:00 pm',
          phone: '+64 9 123 0155',
          currency: 'NZ$',
          menu: [
            { name: 'Espresso', price: 'NZ$4.00' },
            { name: 'Flat White', price: 'NZ$5.00' },
            { name: 'Butter Croissant', price: 'NZ$5.50' },
            { name: 'Avocado on Toast', price: 'NZ$16.00' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Wellington',
          phone: '+64 4 123 0142',
          plans: [
            { name: 'Basic', price: 'NZ$150', per: '/ mo' },
            { name: 'Pro', price: 'NZ$240', per: '/ mo' },
            { name: 'VIP', price: 'NZ$390', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Auckland',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+64 9 123 0177',
          listings: [
            { title: 'Apartment · Ponsonby', meta: '2 bed · 70 m²', price: 'NZ$895,000' },
            { title: 'Villa · Wellington', meta: '3 bed · garden', price: 'NZ$1,050,000' },
            { title: 'House · Christchurch', meta: '4 bed · section', price: 'NZ$720,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+64 9 123 0166',
          treatments: [
            { name: 'Classic facial', price: 'from NZ$110' },
            { name: 'Anti-ageing', price: 'from NZ$165' },
            { name: 'Body treatment', price: 'from NZ$140' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+64 9 123 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    za: {
      code: 'za',
      name: 'South Africa',
      flag: '🇿🇦',
      primaryLanguage: 'en-ZA',
      languages: ['en-ZA'],
      currency: 'ZAR',
      currencySymbol: 'R',
      currencyPosition: 'before',
      phoneCode: '+27',
      phoneExample: '+27 21 123 4567',
      phoneFormat: '## ### ####',
      dateFormat: 'YYYY/MM/DD',
      measurement: 'metric',
      timezone: 'Africa/Johannesburg',
      locale: 'en-ZA',
      regionLabel: 'ZA',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'cellphone',
        zip: 'postal code',
        state: 'province',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 4999,
        growth: 7499,
        pro: 9999,
        display: { starter: 'R4,999', growth: 'R7,499', pro: 'R9,999', range: 'R4,999 – R9,999', from: 'From R4,999 / year' },
      },
      addressExample: '45 Long Street, Cape Town 8001',
      cityExamples: ['Cape Town', 'Johannesburg', 'Durban', 'Pretoria'],
      seo: {
        title: 'NexaSites — AI Websites for South African Businesses',
        description: 'Custom AI-built websites with domain included. From R4,999/year in South Africa.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighbourhood coffee, done properly',
          address: '22 Bree Street, Cape Town 8001',
          hours: 'Mon–Sun 7:00 – 17:00',
          phone: '+27 21 123 0155',
          currency: 'R',
          menu: [
            { name: 'Espresso', price: 'R28' },
            { name: 'Flat White', price: 'R38' },
            { name: 'Butter Croissant', price: 'R35' },
            { name: 'Avo on Toast', price: 'R85' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Johannesburg',
          phone: '+27 11 123 0142',
          plans: [
            { name: 'Basic', price: 'R1,499', per: '/ mo' },
            { name: 'Pro', price: 'R2,499', per: '/ mo' },
            { name: 'VIP', price: 'R3,999', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Cape Town',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+27 21 123 0177',
          listings: [
            { title: 'Apartment · Sea Point', meta: '2 bed · sea view', price: 'R3,850,000' },
            { title: 'House · Johannesburg North', meta: '3 bed · garden', price: 'R2,950,000' },
            { title: 'Townhouse · Durban', meta: '3 bed · security estate', price: 'R2,100,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+27 21 123 0166',
          treatments: [
            { name: 'Classic facial', price: 'from R650' },
            { name: 'Anti-ageing', price: 'from R950' },
            { name: 'Body treatment', price: 'from R800' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+27 21 123 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    sg: {
      code: 'sg',
      name: 'Singapore',
      flag: '🇸🇬',
      primaryLanguage: 'en-SG',
      languages: ['en-SG'],
      currency: 'SGD',
      currencySymbol: 'S$',
      currencyPosition: 'before',
      phoneCode: '+65',
      phoneExample: '+65 6123 4567',
      phoneFormat: '#### ####',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Asia/Singapore',
      locale: 'en-SG',
      regionLabel: 'SG',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'postal code',
        state: 'district',
        city: 'area',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 399,
        growth: 599,
        pro: 799,
        display: { starter: 'S$399', growth: 'S$599', pro: 'S$799', range: 'S$399 – S$799', from: 'From S$399 / year' },
      },
      addressExample: '1 Raffles Place, Singapore 048616',
      cityExamples: ['Marina Bay', 'Orchard', 'Tanjong Pagar', 'Katong'],
      seo: {
        title: 'NexaSites — AI Websites for Singapore Businesses',
        description: 'Custom AI-built websites with domain included. From S$399/year in Singapore.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighbourhood coffee, done properly',
          address: '42 Club Street, Singapore 069419',
          hours: 'Mon–Sun 8:00 – 18:00',
          phone: '+65 6123 0155',
          currency: 'S$',
          menu: [
            { name: 'Espresso', price: 'S$4.50' },
            { name: 'Flat White', price: 'S$5.80' },
            { name: 'Butter Croissant', price: 'S$5.20' },
            { name: 'Avocado Toast', price: 'S$16.00' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Singapore',
          phone: '+65 6123 0142',
          plans: [
            { name: 'Basic', price: 'S$180', per: '/ mo' },
            { name: 'Pro', price: 'S$280', per: '/ mo' },
            { name: 'VIP', price: 'S$450', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Singapore',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+65 6123 0177',
          listings: [
            { title: 'Condo · Tanjong Pagar', meta: '2 bed · 90 m²', price: 'S$1,850,000' },
            { title: 'Apartment · Katong', meta: '3 bed · near MRT', price: 'S$2,200,000' },
            { title: 'Studio · Orchard', meta: '1 bed · city view', price: 'S$1,150,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+65 6123 0166',
          treatments: [
            { name: 'Classic facial', price: 'from S$120' },
            { name: 'Anti-ageing', price: 'from S$180' },
            { name: 'Body treatment', price: 'from S$150' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+65 6123 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    ph: {
      code: 'ph',
      name: 'Philippines',
      flag: '🇵🇭',
      primaryLanguage: 'en-PH',
      languages: ['en-PH'],
      currency: 'PHP',
      currencySymbol: '₱',
      currencyPosition: 'before',
      phoneCode: '+63',
      phoneExample: '+63 2 8123 4567',
      phoneFormat: '# #### ####',
      dateFormat: 'MM/DD/YYYY',
      measurement: 'metric',
      timezone: 'Asia/Manila',
      locale: 'en-PH',
      regionLabel: 'PH',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'ZIP code',
        state: 'province',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 14999,
        growth: 22999,
        pro: 29999,
        display: { starter: '₱14,999', growth: '₱22,999', pro: '₱29,999', range: '₱14,999 – ₱29,999', from: 'From ₱14,999 / year' },
      },
      addressExample: 'Ayala Avenue, Makati City 1226',
      cityExamples: ['Makati', 'BGC', 'Cebu', 'Quezon City'],
      seo: {
        title: 'NexaSites — AI Websites for Philippine Businesses',
        description: 'Custom AI-built websites with domain included. From ₱14,999/year in the Philippines.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighborhood coffee, done properly',
          address: 'Legazpi Village, Makati City',
          hours: 'Mon–Sun 7:00 AM – 9:00 PM',
          phone: '+63 2 8123 0155',
          currency: '₱',
          menu: [
            { name: 'Espresso', price: '₱120' },
            { name: 'Flat White', price: '₱160' },
            { name: 'Butter Croissant', price: '₱140' },
            { name: 'Avocado Toast', price: '₱280' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'BGC, Taguig',
          phone: '+63 2 8123 0142',
          plans: [
            { name: 'Basic', price: '₱4,999', per: '/ mo' },
            { name: 'Pro', price: '₱7,999', per: '/ mo' },
            { name: 'VIP', price: '₱12,999', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Makati',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+63 2 8123 0177',
          listings: [
            { title: 'Condo · BGC', meta: '2 bed · 65 m²', price: '₱12,500,000' },
            { title: 'Townhouse · Quezon City', meta: '3 bed · garage', price: '₱9,800,000' },
            { title: 'Condo · Cebu IT Park', meta: '1 bed · city view', price: '₱6,200,000' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+63 2 8123 0166',
          treatments: [
            { name: 'Classic facial', price: 'from ₱1,800' },
            { name: 'Anti-aging', price: 'from ₱2,800' },
            { name: 'Body treatment', price: 'from ₱2,200' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+63 2 8123 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },

    in: {
      code: 'in',
      name: 'India',
      flag: '🇮🇳',
      primaryLanguage: 'en-IN',
      languages: ['en-IN'],
      currency: 'INR',
      currencySymbol: '₹',
      currencyPosition: 'before',
      phoneCode: '+91',
      phoneExample: '+91 22 1234 5678',
      phoneFormat: '##### #####',
      dateFormat: 'DD/MM/YYYY',
      measurement: 'metric',
      timezone: 'Asia/Kolkata',
      locale: 'en-IN',
      regionLabel: 'IN',
      ctaPrimary: 'Get a free quote',
      ctaSecondary: 'View packages',
      ctaContact: 'Book a call',
      terms: {
        business: 'business',
        website: 'website',
        domain: 'domain',
        phone: 'phone',
        mobile: 'mobile',
        zip: 'PIN code',
        state: 'state',
        city: 'city',
        address: 'address',
        email: 'email',
        contact: 'get in touch',
        pricing: 'pricing',
        package: 'package',
        year: 'year',
        from: 'From',
        perYear: '/ year',
        support: 'support',
        hosting: 'hosting',
      },
      pricing: {
        starter: 24999,
        growth: 37999,
        pro: 49999,
        display: { starter: '₹24,999', growth: '₹37,999', pro: '₹49,999', range: '₹24,999 – ₹49,999', from: 'From ₹24,999 / year' },
      },
      addressExample: 'Bandra Kurla Complex, Mumbai 400051',
      cityExamples: ['Mumbai', 'Bengaluru', 'Delhi NCR', 'Hyderabad'],
      seo: {
        title: 'NexaSites — AI Websites for Indian Businesses',
        description: 'Custom AI-built websites with domain included. From ₹24,999/year across India.',
      },
      demo: {
        cafe: {
          name: 'Harbour Roast',
          tagline: 'Neighbourhood coffee, done properly',
          address: 'Linking Road, Bandra West, Mumbai 400050',
          hours: 'Mon–Sun 8:00 AM – 10:00 PM',
          phone: '+91 22 1234 0155',
          currency: '₹',
          menu: [
            { name: 'Espresso', price: '₹150' },
            { name: 'Flat White', price: '₹220' },
            { name: 'Butter Croissant', price: '₹180' },
            { name: 'Avocado Toast', price: '₹420' },
          ],
        },
        fitness: {
          name: 'Peak Form',
          tagline: 'No excuses. Only results.',
          city: 'Bengaluru',
          phone: '+91 80 1234 0142',
          plans: [
            { name: 'Basic', price: '₹7,999', per: '/ mo' },
            { name: 'Pro', price: '₹12,999', per: '/ mo' },
            { name: 'VIP', price: '₹19,999', per: '/ mo' },
          ],
        },
        studio: {
          name: 'Lumen',
          tagline: 'Design that feels inevitable',
          email: 'hello@lumen.studio',
          city: 'Bengaluru',
        },
        realty: {
          name: 'Summit Homes',
          tagline: 'Find the place that fits',
          phone: '+91 22 1234 0177',
          listings: [
            { title: 'Apartment · Bandra', meta: '2 BHK · 1,100 sq ft', price: '₹2.8 Cr' },
            { title: 'Villa · Whitefield', meta: '3 BHK · garden', price: '₹1.9 Cr' },
            { title: 'Flat · Gurgaon', meta: '3 BHK · society', price: '₹1.6 Cr' },
          ],
        },
        beauty: {
          name: 'Glow Studio',
          tagline: 'Time to glow from within',
          phone: '+91 22 1234 0166',
          treatments: [
            { name: 'Classic facial', price: 'from ₹2,500' },
            { name: 'Anti-ageing', price: 'from ₹4,500' },
            { name: 'Body treatment', price: 'from ₹3,500' },
          ],
        },
        lawyer: {
          name: 'Whitman & Co.',
          tagline: 'Clear counsel. Measured results.',
          phone: '+91 22 1234 0188',
          areas: ['Commercial contracts', 'Property', 'Civil litigation'],
        },
      },
    },
  },
};
